// Custom Views — 4 features for Inventory Demand Forecasting
// VIZ: forecast accuracy line chart, SKU velocity heatmap
// NON-VIZ: replenishment order PDF, forecast rules editor (CRUD)
import express from 'express';

const router = express.Router();

// In-memory store for forecast rules (acts as a CRUD editor backend)
let __rules = [
  { id: 1, sku: 'SKU-1001', safety_stock: 50, lead_time_days: 7, reorder_point: 120, notes: 'High velocity' },
  { id: 2, sku: 'SKU-1002', safety_stock: 30, lead_time_days: 14, reorder_point: 80, notes: 'Seasonal' },
  { id: 3, sku: 'SKU-1003', safety_stock: 75, lead_time_days: 5, reorder_point: 200, notes: 'Critical SKU' },
  { id: 4, sku: 'SKU-1004', safety_stock: 20, lead_time_days: 21, reorder_point: 60, notes: 'Import lead-time' },
  { id: 5, sku: 'SKU-1005', safety_stock: 100, lead_time_days: 3, reorder_point: 250, notes: 'Local supplier' },
];
let __ruleNextId = 6;

// Deterministic pseudo-random helper for repeatable demo data
function seededRand(seed) {
  let x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

// ---------- 1) VIZ: Forecast accuracy line chart data ----------
// GET /api/custom-views/forecast-accuracy
router.get('/forecast-accuracy', (req, res) => {
  try {
    const weeks = 12;
    const data = [];
    for (let i = 1; i <= weeks; i++) {
      const base = 500 + Math.round(seededRand(i) * 200);
      const predicted = base;
      const actual = Math.round(base + (seededRand(i + 100) - 0.5) * 120);
      const errPct = Math.round((Math.abs(predicted - actual) / predicted) * 100);
      data.push({
        week: `W${i}`,
        predicted,
        actual,
        error_pct: errPct,
      });
    }
    const mape = Math.round(
      data.reduce((s, d) => s + d.error_pct, 0) / data.length
    );
    res.json({
      feature: 'forecast-accuracy',
      title: 'Forecast Accuracy (Predicted vs Actual)',
      mape_pct: mape,
      series: data,
    });
  } catch (e) {
    res.status(500).json({ error: e.message || 'forecast-accuracy failed' });
  }
});

// ---------- 2) VIZ: SKU velocity heatmap (SKU x week) ----------
// GET /api/custom-views/sku-velocity-heatmap
router.get('/sku-velocity-heatmap', (req, res) => {
  try {
    const skus = ['SKU-1001', 'SKU-1002', 'SKU-1003', 'SKU-1004', 'SKU-1005', 'SKU-1006', 'SKU-1007', 'SKU-1008'];
    const weeks = 10;
    const rows = skus.map((sku, sIdx) => {
      const cells = [];
      for (let w = 1; w <= weeks; w++) {
        const v = Math.round(seededRand(sIdx * 31 + w) * 100);
        cells.push({ week: `W${w}`, value: v });
      }
      const total = cells.reduce((s, c) => s + c.value, 0);
      return { sku, cells, total };
    });
    res.json({
      feature: 'sku-velocity-heatmap',
      title: 'SKU Velocity Heatmap',
      weeks,
      skus: rows,
    });
  } catch (e) {
    res.status(500).json({ error: e.message || 'sku-velocity-heatmap failed' });
  }
});

// ---------- 3) NON-VIZ: Replenishment order PDF ----------
// GET /api/custom-views/replenishment-pdf?sku=SKU-1001&qty=100
// Returns a minimal valid PDF (application/pdf) representing a purchase order.
router.get('/replenishment-pdf', (req, res) => {
  try {
    const sku = (req.query.sku || 'SKU-1001').toString().slice(0, 40);
    const qty = parseInt(req.query.qty, 10) || 100;
    const supplier = (req.query.supplier || 'Default Supplier').toString().slice(0, 60);
    const date = new Date().toISOString().slice(0, 10);
    const poNum = 'PO-' + Date.now().toString().slice(-8);

    const lines = [
      'Replenishment Purchase Order',
      `PO Number: ${poNum}`,
      `Date: ${date}`,
      `Supplier: ${supplier}`,
      `SKU: ${sku}`,
      `Quantity: ${qty}`,
      '------------------------------',
      'Generated by AI Inventory Forecasting',
    ];

    // Build a minimal PDF (one page, Helvetica) by hand.
    const escape = (s) => s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    let content = 'BT\n/F1 14 Tf\n72 760 Td\n';
    lines.forEach((ln, i) => {
      content += (i === 0 ? '' : '0 -20 Td\n') + `(${escape(ln)}) Tj\n`;
    });
    content += 'ET\n';
    const contentLen = Buffer.byteLength(content, 'utf8');

    const objects = [];
    objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');
    objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');
    objects.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n');
    objects.push(`4 0 obj\n<< /Length ${contentLen} >>\nstream\n${content}endstream\nendobj\n`);
    objects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n');

    const header = '%PDF-1.4\n';
    let body = header;
    const offsets = [];
    for (const obj of objects) {
      offsets.push(Buffer.byteLength(body, 'utf8'));
      body += obj;
    }
    const xrefStart = Buffer.byteLength(body, 'utf8');
    let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    for (const off of offsets) {
      xref += String(off).padStart(10, '0') + ' 00000 n \n';
    }
    const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
    const pdf = body + xref + trailer;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${poNum}.pdf"`);
    res.send(Buffer.from(pdf, 'utf8'));
  } catch (e) {
    res.status(500).json({ error: e.message || 'replenishment-pdf failed' });
  }
});

// ---------- 4) NON-VIZ: Forecast rules editor (CRUD) ----------
// GET   /api/custom-views/forecast-rules
// POST  /api/custom-views/forecast-rules           { sku, safety_stock, lead_time_days, reorder_point, notes }
// PUT   /api/custom-views/forecast-rules/:id
// DELETE /api/custom-views/forecast-rules/:id
router.get('/forecast-rules', (req, res) => {
  res.json({
    feature: 'forecast-rules',
    title: 'Forecast Rules Editor',
    count: __rules.length,
    rules: __rules,
  });
});

router.post('/forecast-rules', (req, res) => {
  try {
    const body = req.body || {};
    const sku = (body.sku || '').toString().trim();
    if (!sku) return res.status(400).json({ error: 'sku required' });
    const rule = {
      id: __ruleNextId++,
      sku,
      safety_stock: Number(body.safety_stock) || 0,
      lead_time_days: Number(body.lead_time_days) || 0,
      reorder_point: Number(body.reorder_point) || 0,
      notes: (body.notes || '').toString(),
    };
    __rules.push(rule);
    res.status(201).json({ rule });
  } catch (e) {
    res.status(500).json({ error: e.message || 'create rule failed' });
  }
});

router.put('/forecast-rules/:id', (req, res) => {
  const id = parseInt(req.params.id, 10);
  const idx = __rules.findIndex((r) => r.id === id);
  if (idx === -1) return res.status(404).json({ error: 'rule not found' });
  const body = req.body || {};
  __rules[idx] = {
    ...__rules[idx],
    ...(body.sku !== undefined && { sku: String(body.sku) }),
    ...(body.safety_stock !== undefined && { safety_stock: Number(body.safety_stock) }),
    ...(body.lead_time_days !== undefined && { lead_time_days: Number(body.lead_time_days) }),
    ...(body.reorder_point !== undefined && { reorder_point: Number(body.reorder_point) }),
    ...(body.notes !== undefined && { notes: String(body.notes) }),
  };
  res.json({ rule: __rules[idx] });
});

router.delete('/forecast-rules/:id', (req, res) => {
  const id = parseInt(req.params.id, 10);
  const before = __rules.length;
  __rules = __rules.filter((r) => r.id !== id);
  if (__rules.length === before) return res.status(404).json({ error: 'rule not found' });
  res.json({ deleted: true, id });
});

export default router;
